Web_banThucPhamSach/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web_banThucPhamSach.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Tên đăng nhập")]
        public string userName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Mật khẩu")]
        public string password { get; set; }
    }
}

Web_banThucPhamSach/Controllers/FunctionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Globalization;
using System.Security.Claims;
using Web_banThucPhamSach.Data;
using Web_banThucPhamSach.Models;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Web_banThucPhamSach.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using System.Net;

namespace Web_banThucPhamSach.Controllers
{
    public class FunctionController : Controller
    {
        private WebBanThucPhamSachContext _context;
        public FunctionController(WebBanThucPhamSachContext context)
        {
            _context = context;
        }
        public IActionResult Cart()
        {
            var user = User.FindFirst("Id")?.Value;
            if (user == null)
            {
                return RedirectToAction("Login", "TrangChu");
            }
            var cart = GetCartItems();
            ViewBag.TotalQuantity = TotalQuantityInCart();
            return View(cart);
        }
        [Route("addCart/{productId?}", Name = "addcart")]
        public IActionResult AddToCart([FromRoute] string productId)
        {

            var product = _context.Products
                .AsNoTracking()
                .Where(c => c.Id == productId)
                .FirstOrDefault();
            if (product == null)
            {
                return NotFound("Không tìm thấy sản phẩm");
            }
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.ProductId == productId);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cartitem.Quantity++;
                cartitem.AllTotal = cartitem.Quantity * (cartitem.Product?.Price ?? 0);
            }
            else
            {
                //  Thêm mới
                //cart.Add(new Cart() { ProductId = productId, Quantity = 1, Product = product });
                cart.Add(new Cart()
                {
                    ProductId = productId,
                    Quantity = 1,
                    Product = product,
                    AllTotal = product.Price // Khởi tạo tổng tiền với số lượng 1
                });
            }

            // Lưu cart vào Session
            SaveCartSession(cart);
            ViewBag.QuantityCart = TotalQuantityInCart();
            // Chuyển đến trang hiện thị Cart
            return RedirectToAction(nameof(Cart));
        }

        public const string Cartkey = "cart";
        List<Cart> GetCartItems()
        {
            var session = HttpContext.Session;
            string jsoncart = session.GetString(Cartkey);
            if (jsoncart != null)
            {
                try
                {
                    return JsonConvert.DeserializeObject<List<Cart>>(jsoncart);
                }
                catch (JsonException)
                {
                    // Xử lý lỗi khi đọc dữ liệu JSON
                    session.Remove(Cartkey); // Xóa giỏ hàng không hợp lệ
                    return new List<Cart>();
                }
            }
            return new List<Cart>();
        }
        void SaveCartSession(List<Cart> ls)
        {
            var session = HttpContext.Session;
            string jsoncart = JsonConvert.SerializeObject(ls);
            session.SetString(Cartkey, jsoncart);
        }

        [Route("/RemoveCart/{productId}", Name = "removecart")]
        public IActionResult RemoveCart([FromRoute] string productId)
        {
            var cart = GetCartItems();
            var cartItem = cart.SingleOrDefault(x => x.ProductId == productId);
            if (cartItem != null)
            {
                cart.Remove(cartItem);
            }
            SaveCartSession(cart);  // Lưu giỏ hàng sau khi xóa
            return RedirectToAction(nameof(Cart));
        }
        [Route("/updatecart", Name = "updatecart")]
        [HttpPost]
        public IActionResult UpdateCart([FromForm] string productId, [FromForm] int quantity)
        {
            if (quantity < 1)
            {
                return Json(new { success = false, message = "Số lượng phải là số nguyên dương." });
            }
            var cart = GetCartItems();
            var cartItem = cart.SingleOrDefault(x => x.ProductId == productId);

            if (cartItem != null)
            {
                // Cập nhật số lượng và tổng tiền cho sản phẩm
                cartItem.Quantity = quantity;
                cartItem.AllTotal = cartItem.Quantity * (cartItem.Product?.Price ?? 0);
            }

            // Lưu lại giỏ hàng vào session sau khi cập nhật
            SaveCartSession(cart);

            // Tính tổng tiền cho tất cả sản phẩm trong giỏ
            var cartTotal = cart.Sum(item => item.Quantity * (item.Product?.Price ?? 0));

            // Trả về JSON để cập nhật UI
            return Json(new
            {
                success = true,
                total = cartItem.AllTotal,
                cartTotal = cartTotal,
                cartItems = cart.Select(item => new
                {
                    productId = item.ProductId,
                    quantity = item.Quantity,
                    product = item.Product
                }).ToList()
            });
        }
        public int TotalQuantityInCart()
        {
            var cart = GetCartItems();
            return cart.Sum(c => c.Quantity);
        }
        public JsonResult BagCart()
        {
            int total_item = TotalQuantityInCart();
            return Json(new { quantity = total_item });
        }
        [HttpPost]
        public IActionResult ThanhToan()
        {
            var cartItems = GetCartItems(); // Giả sử phương thức này lấy danh sách sản phẩm trong giỏ hàng
            if (cartItems == null || !cartItems.Any())
            {
                return View("Error", "Giỏ hàng trống.");
            }
            // Lấy thông tin người dùng hiện tại từ Claims
            var userId = User.FindFirst("Id")?.Value;
            if (userId == null)
            {
                return NotFound("Người dùng không xác định.");
            }
            var user = _context.Users
        .Include(u => u.BankAccounts) // Bao gồm danh sách tài khoản ngân hàng
        .FirstOrDefault(u => u.Id == userId);

            if (user == null)
            {
                return NotFound("Người dùng không tồn tại.");
            }

            var viewModel = new CheckoutViewModel
            {
                CartItems = cartItems,
                User = user
            };

            return View(viewModel); // Trả về view với CheckoutViewModel
        }
        public string GenerateRandomId(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"; // Có thể thay đổi theo nhu cầu
            Random random = new Random();
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        [HttpPost]
        public IActionResult CreateOrder([Bind("PaymentMethod")] Order order, string note)
        {
            try
            {
                var cart = GetCartItems();
                if (cart == null || !cart.Any())
                {
                    ModelState.AddModelError("", "Giỏ hàng trống. Vui lòng thêm sản phẩm.");
                    return RedirectToAction(nameof(Cart));
                }

                order.Id = GenerateRandomId(5);
                order.Fullname = User.Identity.Name;
                order.PhoneNumber = User.FindFirst("PhoneNumber")?.Value;
                order.Address = User.FindFirst("Address")?.Value;
                order.TotalMoney = cart.Sum(item => item.Quantity * item.Product.Price);
                order.OrderDate = DateTime.Now;
                order.Note = note;
                order.Status = 0; // Đơn hàng mới

                // Lấy phương thức thanh toán từ form và xử lý
                var paymentMethod = Request.Form["PaymentMethod"];
                if (string.IsNullOrEmpty(paymentMethod))
                {
                    ModelState.AddModelError("", "Vui lòng chọn phương thức thanh toán.");
                    return View();
                }
                order.PaymentMethod = paymentMethod;

                // Thiết lập UserId cho đơn hàng
                var userId = User.FindFirst("Id")?.Value;
                if (userId == null)
                {
                    return NotFound("Không tìm thấy ID người dùng trong claims");
                }
                order.UserId = userId;

                _context.Orders.Add(order);

                foreach (var item in cart)
                {
                    var orderDetail = new OrderDetail
                    {
                        Id = GenerateRandomId(5),
                        OrderId = order.Id,
                        ProductId = item.Product.Id,
                        Price = item.Product.Price,
                        NumberProducts = item.Quantity,
                        TotalMoney = item.Quantity * item.Product.Price
                    };
                    _context.OrderDetails.Add(orderDetail);

                    var product = _context.Products.FirstOrDefault(p => p.Id == item.Product.Id);
                    if (product != null)
                    {
                        product.Number -= item.Quantity; // Giảm số lượng sản phẩm
                        if (product.Number < 0)
                        {
                            ModelState.AddModelError("", "Sản phẩm " + product.Title +" không đủ số lượng trong kho.");
                            return View("ThanhToan"); // Trả về trang hiện tại nếu sản phẩm không đủ
                        }
                    }
                }

                _context.SaveChanges();

Web_banThucPhamSach/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web_banThucPhamSach.Data;
using Web_banThucPhamSach.Models;

namespace Web_banThucPhamSach.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly WebBanThucPhamSachContext _context;

        public UsersController(WebBanThucPhamSachContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index(int pageIndex = 1, int pageSize = 5)
        {
            var webBanThucPhamSachContext = _context.Users.Include(u => u.Role);
            /*return View(await webBanThucPhamSachContext.ToListAsync());*/
            return View(await PaginatedListViewModel<User>.FromQueryAsync(webBanThucPhamSachContext, pageIndex, pageSize));
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fullname,Email,PhoneNumber,Address,Password,RoleId,CreateAt,UpdateAt,UserName")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        public string GenerateRandomId(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"; // Có thể thay đổi theo nhu cầu
            Random random = new Random();
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Register([Bind("Id,Fullname,Email,PhoneNumber,Address,Password,RoleId,CreateAt,UpdateAt,UserName")] User user)
        {
            user.Id = GenerateRandomId(5);
            user.Fullname = " ";
            user.Email = " ";
            user.RoleId = 2;
            user.Address = " ";
            user.CreateAt = DateTime.Now;
            user.UpdateAt = DateTime.Now;

            ModelState.ClearValidationState(nameof(user.Id));
            ModelState.ClearValidationState(nameof(user.Fullname));
            ModelState.ClearValidationState(nameof(user.Email));
            ModelState.ClearValidationState(nameof(user.RoleId));
            ModelState.ClearValidationState(nameof(user.Address));
            TryValidateModel(user, nameof(user.Id));
            TryValidateModel(user, nameof(user.Fullname));
            TryValidateModel(user, nameof(user.Email));
            TryValidateModel(user, nameof(user.RoleId));
            TryValidateModel(user, nameof(user.Address));
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction("Login", "TrangChu");
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View("~/Views/TrangChu/Index.cshtml");
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Fullname,Email,PhoneNumber,Address,Password,RoleId,CreateAt,UpdateAt,UserName")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Web_banThucPhamSach/Views/TrangChu/Category.cshtml
@model Web_banThucPhamSach.Models.PaginatedListViewModel<Web_banThucPhamSach.Data.Product>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TrangChu.cshtml";
}
<style>
    #chuyentrang {
        display: flex;
        flex-direction: column;
        align-items: center;
        margin-top: 20px;
    }

        #chuyentrang .btn-group {
            margin-bottom: 10px;
        }

        #chuyentrang .btn {
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 50%;
            transition: background-color 0.3s, color 0.3s;
            text-transform: uppercase;
        }

        #chuyentrang .btn-outline-primary {
            color: black;
            border: 2px solid green;
            background-color: seagreen;
        }

            #chuyentrang .btn-outline-primary:hover {
                color: white;
                background-color: darkgreen;
            }

        #chuyentrang .btn:disabled,
        #chuyentrang .btn[disabled] {
            color: #aaa;
            background-color: #f5f5f5;
            border-color: #ccc;
            cursor: not-allowed;
        }

        #chuyentrang .text-primary {
            font-size: 14px;
            color: #333;
            font-weight: 500;
        }

</style>
<section id="search-banner1">
    <form method="get" asp-controller="TrangChu" asp-action="Index" class="search-box1">
        <i class="fa-solid fa-magnifying-glass"></i>
        <input type="text" class="search-input1" placeholder="Tìm kiếm sản phẩm" name="search" required>
        <input type="submit" class="search-btn1" value="Search" name="" id="">
    </form>
</section>
<section id="category">
    <div class="category-heading">
        <h2>Category</h2>
        <span>All</span>
    </div>

    <!-- box-container -->
    <div class="category-container">
        <a asp-controller="TrangChu" asp-action="Category" asp-route-category="Cá và thịt" class="category-box">
            <img src="~/images/fish.png" alt="Fish">
            <span>Cá và thịt</span>
        </a>

        <a asp-controller="TrangChu" asp-action="Category" asp-route-category="Rau củ" class="category-box">
            <img src="~/images/Vegetables.png" alt="Vegatables">
            <span>Rau củ</span>
        </a>

        <a asp-controller="TrangChu" asp-action="Category" asp-route-category="Trái cây" class="category-box">
            <img src="~/images/TraiCay.png" alt="fruit">
            <span>Trái cây</span>
        </a>

        <a asp-controller="TrangChu" asp-action="Category" asp-route-category="Sữa" class="category-box">
            <img src="~/images/milk.png" alt="Milk">
            <span>Sữa</span>
        </a>

        <a asp-controller="TrangChu" asp-action="Category" asp-route-category="Hạt giống" class="category-box">
            <img src="~/images/Gardening.png" alt="Gardening">
            <span>Hạt giống</span>
        </a>

        <a asp-controller="TrangChu" asp-action="Category" asp-route-category="Cá và thịt" class="category-box ">
            <img src="~/images/cooking.png" alt="Cooking">
            <span>Nấu ăn</span>
        </a>

        <a asp-controller="TrangChu" asp-action="Category" asp-route-category="Beauty" class="category-box @(ViewBag.CurrentCategory == "Làm đẹp" ? "active" : "")">
            <img src="~/images/beauty.png" alt="Beauty">
            <span>Làm đẹp</span>
        </a>
    </div>
</section>
<!-- popular product -->
<section id="popular-product">
    <div class="product-headding">
        <h3>Tất cả sản phẩm</h3>
    </div>

    <div class="product-container">
        @foreach (var sp in Model)
        {
            <div class="product-box">
                <a asp-controller="Function" asp-action="TT_Product" asp-route-id="@sp.Id">
                    @if (!string.IsNullOrEmpty(sp.Image))
                    {
                        var imagePaths = sp.Image.Split(',');
                        <img src="@Url.Content(imagePaths[0])" alt="@sp.Title" />
                    }
                    <strong>@sp.Title</strong>
                </a>
                <span class="quantity">@sp.Number KG</span>
                <span class="price">@sp.Price</span>
                <a asp-controller="Function" asp-action="AddToCart" asp-route-productid="@sp.Id" class="cart-btn">
                    <i class="fa-solid fa-cart-shopping"></i> Thêm vào giỏ hàng
                </a>
                <a href="" class="like-btn"><i class="fa-regular fa-heart"></i></a>
            </div>
        }
    </div>
    <div id="chuyentrang">
        <div class="btn-group me-2" role="alert " group>
            <a class="btn btn-outline-primary @Model.PreviouDisabledAttr"
               asp-route-pageIndex="1"
               asp-route-pageSize="@Model.PageSize">1</a>

            <a class="btn btn-outline-primary @Model.PreviouDisabledAttr"
               asp-route-pageIndex="@Model.PrevPageIndex"
               asp-route-pageSize="@Model.PageSize"><</a>

            <a class="btn btn-outline-primary @Model.NextDisabledAttr"
               asp-route-pageIndex="@Model.NextPageIndex"
               asp-route-pageSize="@Model.PageSize">></a>
        </div>
        <div class="text-primary">
            Displaying @Model.ItemIndexFrom to @Model.ItemIndexTo of @Model.TotalCount items
        </div>
    </div>

</section>

Web_banThucPhamSach/Views/TrangChu/Login.cshtml
@model Web_banThucPhamSach.Models.LoginViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="~/css/Login.css">
</head>
<style>
    .error-message {
        display: none;
        position: absolute;
        top: 20px; /* Khoảng cách từ trên xuống */
        left: 50%;
        transform: translateX(-50%);
        background-color: rgba(255, 0, 0, 0.8); /* Màu nền đỏ trong suốt */
        color: white; /* Màu chữ trắng */
        padding: 15px;
        border-radius: 5px; /* Bo tròn góc */
        width: 80%; /* Chiều rộng khung */
        max-width: 600px; /* Chiều rộng tối đa */
        text-align: center; /* Canh giữa chữ */
        z-index: 1000; /* Đảm bảo nó hiển thị trên cùng */
    }
</style>
<body>
    @*  <form asp-controller="TrangChu" asp-action="Login" asp-route-returnurt="@ViewData["ReturnUrl"]" method="post" class="form-horizontal" action="/Users/Register"> *@
    <div class="container">
        <img src="~/images/hinhnen.jpg" alt="Hình nền" class="hinhnen">
        <div id="error-message" class="error-message" style="display: @(ViewData.ModelState.IsValid ? "none" : "block")">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
        <div class="signin-signup">
            <!-- sing in -->
            <form class="sign-in-form" asp-controller="TrangChu" asp-action="Login" asp-route-returnurt="@ViewData["ReturnUrl"]" method="post">
                <h2 class="title">Đăng nhập</h2>
                <div class="input-field">
                    <i class="fa-solid fa-user"></i>
                    <input type="text" placeholder="Nhập tên đăng nhập" name="username">
                </div>

                <div class="input-field">
                    <i class="fa-solid fa-lock"></i>
                    <input type="password" placeholder="Nhập mật khẩu" name="password">
                </div>

                <input type="submit" value="Sign in" class="btn">
                <p>Đăng nhập tài khoản với các trang mạng như</p>
                <div class="social-media">
                    <a href="" class="social-icon"><i class="fa-brands fa-facebook"></i></a>
                    <a href="" class="social-icon"><i class="fa-brands fa-twitter"></i></a>
                    <a href="" class="social-icon"><i class="fa-brands fa-google"></i></a>
                    <a href="" class="social-icon"><i class="fa-brands fa-instagram"></i></a>
                </div>
            </form>
            <!-- sing up -->
            <form class="sign-up-form" method="post" asp-controller="Users" asp-action="Register">
                <h2 class="title">Đăng ký</h2>
                <div class="input-field">
                    <i class="fa-solid fa-user"></i>
                    <input type="text" placeholder="Nhập tên đăng ký" name="username" id="surname">
                </div>
                <div class="input-field">
                    <i class="fa-solid fa-envelope"></i>
                    <input type="text" placeholder="Nhập số điện thoại đăng ký" name="PhoneNumber" id="phonenumber">
                </div>
                <div class="input-field">
                    <i class="fa-solid fa-lock"></i>
                    <input type="password" placeholder="Nhập mật khẩu" name="password" id="password">
                </div>

                <input type="submit" value="Sign up" class="btn">
                <p>Đăng ký tài khoản với các trang mạng như</p>
                <div class="social-media">
                    <a href="" class="social-icon"><i class="fa-brands fa-facebook"></i></a>
                    <a href="" class="social-icon"><i class="fa-brands fa-twitter"></i></a>
                    <a href="" class="social-icon"><i class="fa-brands fa-google"></i></a>
                    <a href="" class="social-icon"><i class="fa-brands fa-instagram"></i></a>
                </div>
            </form>
        </div>

        <div class="panel-container">
            <div class="panel panel-left">
                <div class="content">
                    <h3>Bạn đã có tài khoản tại MinhTran?</h3>
                    <p>Bạn đã có một tài khoản tại cửa hàng MinhTran? <br> Điều đó thật tuyệt!!!</p>
                    <button class="btn" id="sign_in_btn">Sign in</button>
                </div>
                <img src="~/images/image1.svg" alt="image" class="image">
            </div>

            <div class="panel panel-right">
                <div class="content">
                    <h3>Bạn muốn bắt đầu mua sắm MinhTran?</h3>
                    <p>Bạn muốn được mua hàng tại cửa hàng MinhTran? <br> Vậy thực hiện đăng ký tài khoản nào!!!</p>
                    <button class="btn" id="sign_up_btn">Sign up</button>
                </div>
                <img src="~/images/image2.svg" alt="image" class="image">
            </div>
        </div>
    </div>
    @*     </form> *@
    <script src="~/js/Login-up.js"></script>
</body>

</html>