Web_banThucPhamSach/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web_banThucPhamSach.Data;
using Web_banThucPhamSach.Models;

namespace Web_banThucPhamSach.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrdersController : Controller
    {
        private readonly WebBanThucPhamSachContext _context;

        public OrdersController(WebBanThucPhamSachContext context)
        {
            _context = context;
        }
        public IActionResult OrderList(string title)
        {
            var orders = _context.Orders
                .Include(o => o.OrderDetails)
                .ThenInclude(od => od.Product)
                .AsQueryable();

            if (!string.IsNullOrEmpty(title))
            {
                orders = orders.Where(o => o.OrderDetails.Any(od => od.Product.Title == title));
            }


            return View(orders.ToList());
        }


        // GET: Orders
        public async Task<IActionResult> Index(string accountType, string paymentMethod,string status, int pageIndex = 1, int pageSize = 5)
        {
            var webBanThucPhamSachContext = _context.Orders
        .Include(o => o.OrderDetails)
        .ThenInclude(od => od.Product)
        .Include(o => o.User)
        .ThenInclude(u => u.BankAccounts)
        .AsQueryable();

            // Lọc theo AccountType từ BankAccount
            if (!string.IsNullOrEmpty(accountType) && accountType != "All")
            {
                webBanThucPhamSachContext = webBanThucPhamSachContext
                    .Where(o => o.User.BankAccounts.Any(b => b.AccountType == accountType));
            }

            // Lọc đơn hàng theo hình thức thanh toán nếu có
            if (!string.IsNullOrEmpty(paymentMethod) && paymentMethod != "All")
            {
                webBanThucPhamSachContext = webBanThucPhamSachContext.Where(o => o.PaymentMethod == paymentMethod);
            }
            // Lọc theo trạng thái đơn hàng
            if (!string.IsNullOrEmpty(status) && status != "All")
            {
                if (status == "Pending")
                {
                    webBanThucPhamSachContext = webBanThucPhamSachContext.Where(o => o.Status == 0); // Giả định 0 là 'chưa duyệt'
                }
                else if (status == "Approved")
                {
                    webBanThucPhamSachContext = webBanThucPhamSachContext.Where(o => o.Status == 1); // Giả định 1 là 'đã duyệt'
                }
                else if (status == "Completed")
                {
                    webBanThucPhamSachContext = webBanThucPhamSachContext.Where(o => o.Status == 2); // Hoàn thành
                }
            }
            /*webBanThucPhamSachContext = webBanThucPhamSachContext.Include(o => o.OrderDetails);*/
            /*return View(await _context.Orders.ToListAsync());*/
            return View(await PaginatedListViewModel<Order>.FromQueryAsync(webBanThucPhamSachContext, pageIndex, pageSize));
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            /*var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.Id == id);*/
            var order = await _context.Orders
                .Include(o => o.OrderDetails)
                .ThenInclude(od => od.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fullname,Email,PhoneNumber,Address,Note,OrderDate,Status,TotalMoney,PaymentMethod")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Fullname,Email,PhoneNumber,Address,Note,OrderDate,Status,TotalMoney,PaymentMethod")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }



        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            //var order = await _context.Orders.FindAsync(id);
            var order = await _context.Orders.Include(o => o.OrderDetails).FirstOrDefaultAsync(o => o.Id == id);
            if (order != null)
            {
                _context.OrderDetails.RemoveRange(order.OrderDetails);  // Xóa tất cả các chi tiết đơn hàng liên quan
                _context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(string id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }

        [HttpPost]
        public IActionResult ApproveOrder(string id)
        {
            var order = _context.Orders.FirstOrDefault(o => o.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            order.Status = 1; // Giả định trạng thái '1' là đã đóng gói hoặc duyệt đơn thành công
            _context.SaveChanges();

            return RedirectToAction(nameof(Index)); // Trở về trang quản lý đơn hàng
        }
        [HttpPost]
        public IActionResult ConfirmReceipt(string orderId)
        {
            var userId = User.FindFirst("Id")?.Value;
            if (userId == null)
            {
                return Json(new { success = false, message = "Không tìm thấy ID người dùng." });
            }

            var order = _context.Orders.FirstOrDefault(o => o.Id == orderId && o.UserId == userId);

            if (order == null || order.Status != 1)  // Kiểm tra trạng thái đơn hàng (chỉ cho phép hoàn thành đơn hàng đang xử lý)
            {
                return Json(new { success = false, message = "Đơn hàng không tồn tại hoặc không thể xác nhận." });
            }

            order.Status = 2;  // Đặt trạng thái thành "Hoàn thành"
            _context.SaveChanges();

            return Json(new { success = true, message = "Đơn hàng đã được xác nhận hoàn thành." });
        }
    }
}

Web_banThucPhamSach/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web_banThucPhamSach.Data;
using Web_banThucPhamSach.Models;

namespace Web_banThucPhamSach.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly WebBanThucPhamSachContext _context;

        public UsersController(WebBanThucPhamSachContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index(int pageIndex = 1, int pageSize = 5)
        {
            var webBanThucPhamSachContext = _context.Users.Include(u => u.Role);
            /*return View(await webBanThucPhamSachContext.ToListAsync());*/
            return View(await PaginatedListViewModel<User>.FromQueryAsync(webBanThucPhamSachContext, pageIndex, pageSize));
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fullname,Email,PhoneNumber,Address,Password,RoleId,CreateAt,UpdateAt,UserName")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        public string GenerateRandomId(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"; // Có thể thay đổi theo nhu cầu
            Random random = new Random();
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Register([Bind("Id,Fullname,Email,PhoneNumber,Address,Password,RoleId,CreateAt,UpdateAt,UserName")] User user)
        {
            user.Id = GenerateRandomId(5);
            user.Fullname = " ";
            user.Email = " ";
            user.RoleId = 2;
            user.Address = " ";
            user.CreateAt = DateTime.Now;
            user.UpdateAt = DateTime.Now;

            ModelState.ClearValidationState(nameof(user.Id));
            ModelState.ClearValidationState(nameof(user.Fullname));
            ModelState.ClearValidationState(nameof(user.Email));
            ModelState.ClearValidationState(nameof(user.RoleId));
            ModelState.ClearValidationState(nameof(user.Address));
            TryValidateModel(user, nameof(user.Id));
            TryValidateModel(user, nameof(user.Fullname));
            TryValidateModel(user, nameof(user.Email));
            TryValidateModel(user, nameof(user.RoleId));
            TryValidateModel(user, nameof(user.Address));
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction("Login", "TrangChu");
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View("~/Views/TrangChu/Index.cshtml");
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Fullname,Email,PhoneNumber,Address,Password,RoleId,CreateAt,UpdateAt,UserName")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Web_banThucPhamSach/Views/Shared/_Admin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="~/css/admin.css" rel="stylesheet" />
</head>
<body data-theme="@ViewData["theme"]">
    <nav class="navigation">
        <!-- logo -->
        <a href="/TrangChu" class="logo"><span>M</span>inhTran</a>

        <!-- menu -->
        <ul class="menu">
            <li><a href="/TrangChu" class="active">Trang chủ</a></li>
            <li><a href="#category">Danh mục sản phẩm</a></li>
            <li><a href="#popular-product">Sản phẩm</a></li>
            <li><a asp-area="" asp-controller="TrangChu" asp-action="About">Thông tin</a></li>
            <li>
                @if (!User.Identity.IsAuthenticated) // Nếu người dùng chưa đăng nhập
                {
                    <a asp-area="" asp-controller="TrangChu" asp-action="Login">Đăng nhập</a>
                }
                else // Nếu người dùng đã đăng nhập
                {
                    <div class="img-account">
                        <img src="~/images/client-1.jpg" alt="">
                    </div>
                    <div class="dropdown">
                        <div class="dropbtn">@User.Identity.Name</div>
                        <div class="dropdown-content">
                            <a a asp-area="" asp-controller="Function" asp-action="Profile">Profile</a>
                            <a href="/TrangChu/Logout">Logout</a>
                        </div>
                    </div>
                }
            </li>
        </ul>

        <div class="right-nav">
            <a href="" class="like"><i class="fa-solid fa-heart"></i><span>0</span></a>
            <a href="" class="cart"><i class="fa-solid fa-cart-plus"></i><span>0</span></a>
        </div>
    </nav>
    <div id="main-body">
        <div class="main-screenAdmin">
            <div class="sidebar">
                <div class="account">
                    <div class="img-account">
                        <img src="~/images/client-1.jpg" alt="">
                        <p>Minh Trân</p>
                    </div>
                </div>
                <div class="menu-function">
                    <a href="/Admin" onclick="showContent('dashboard')">Thông báo chung</a>
                    <a asp-area="" asp-controller="Users" asp-action="Index" onclick="showContent('Manager-Customer')">Quản lý khách hàng</a>
                    <a asp-area="" asp-controller="Admin" asp-action="FunctionChat" onclick="showContent('Chat-with-Customer')">Nhắn tin</a>
                    <a asp-area="" asp-controller="Staffs" asp-action="Index" onclick="showContent('Manager-staff')">Quản lý nhân viên</a>
                    <a asp-area="" asp-controller="Products" asp-action="Index" onclick="showContent('Manager-Product')">Quản lý sản phẩm</a>
                    <a asp-area="" asp-controller="Admin" asp-action="Review" onclick="showContent('content-management')">Quản lý nội dung</a>
                    <a asp-area="" asp-controller="Orders" asp-action="Index" onclick="showContent('order-management')">Quản lý đơn hàng và thanh toán</a>
                    <a asp-area="" asp-controller="Admin" asp-action="ThongKe" onclick="showContent('report-management')">Báo cáo thống kê</a>
                    <a asp-area="" asp-controller="InputWarehouses" asp-action="Index" onclick="showContent('PhanQuyen')">Quản lý nhập kho</a>
                    <a asp-area="" asp-controller="Admin" asp-action="Setting" onclick="showContent('setting')">Cài đặt</a>
                </div>
            </div>
        </div>
        @RenderBody()
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/js/admin.js"></script>
    <script type="text/javascript" src="~/js/theme.js" asp-append-version="true"></script>
</body>
</html>

Web_banThucPhamSach/Views/Shared/_Profile.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bán thực phẩm sạch</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link href="~/css/full.css" rel="stylesheet" />
    <link href="~/css/about.css" rel="stylesheet" />
    <link href="~/css/profileme.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body data-theme="@ViewData["theme"]">
    <nav class="navigation">
        <!-- logo -->
        <a href="/TrangChu" class="logo"><span>M</span>inhTran</a>

        <!-- menu -->
        <ul class="menu">
            <li><a href="/TrangChu" class="active">Trang chủ</a></li>
            <li><a href="#category">Danh mục sản phẩm</a></li>
            <li><a href="#popular-product">Sản phẩm</a></li>
            <li><a asp-area="" asp-controller="TrangChu" asp-action="About">Thông tin</a></li>
            <li>
                @if (!User.Identity.IsAuthenticated) // Nếu người dùng chưa đăng nhập
                {
                    <a asp-area="" asp-controller="TrangChu" asp-action="Login">Đăng nhập</a>
                }
                else // Nếu người dùng đã đăng nhập
                {
                    <div class="img-account">
                        <img src="~/images/client-1.jpg" alt="">
                    </div>
                    <div class="dropdown">
                        <div class="dropbtn">@User.Identity.Name</div>
                        <div class="dropdown-content">
                            <a asp-area="" asp-controller="Function" asp-action="Profile" asp-route-id="@User.FindFirst("Id")?.Value">Profile</a>
                            <a href="/TrangChu/Logout">Logout</a>
                        </div>
                    </div>
                }
            </li>
        </ul>

        <div class="right-nav">
            <a href="#" class="like"><i class="fa-solid fa-heart"></i><span>0</span></a>
            <a asp-controller="Function" asp-action="Cart" class="cart"><i class="fa-solid fa-cart-plus"></i><span id="cartQuantity">@ViewBag.QuantityCart</span></a>
        </div>
    </nav>

    <section id="search2">
        <div class="search2">
            <div class="search-banner-text2">
                <div action="" class="search-box2">
                    <i class="fa-solid fa-magnifying-glass"></i>
                    <input type="text" class="search-input2" placeholder="Tìm kiếm sản phẩm" name="search"
                           required>
                    <input type="submit" class="search-btn2" value="Search" name="" id="">
                </div>
            </div>
        </div>
    </section>
    <section id="main-profile">
        <div class="sidebar">
            <div class="account">
                <div class="img-account">
                    <i class="fa-solid fa-user"></i>
                </div>
                <div class="name-profile">
                    <div><h3>Minh Trân</h3></div>
                    <div class="edit">
                        <i class="fa-regular fa-pen-to-square"></i>
                    </div>
                </div>
            </div>
            <a asp-controller="Function" asp-action="Profile" onclick="showContent('personal-info')">Thông tin cá nhân</a>
            <a asp-controller="Function" asp-action="AllOrderUser" onclick="showContent('orders')">Đơn hàng</a>
            <a asp-controller="Function" asp-action="LienKetNganHang" onclick="showContent('permissions')">Liên kết ngân hàng</a>
            <a href="#" onclick="showContent('setting')">Cài đặt</a>
        </div>

        <div class="content">
            @RenderBody()
            <div id="setting" class="hidden">
                <h2>Cài đặt</h2>
                <p>Đây là thông tin cài đặt của bạn.</p>
            </div>
        </div>
    </section>
        <footer id="footer">
            <div class="footer-container">

                <!-- logo-container -->
                <div class="footer-logo">
                    <a href=""><span>M</span>inhTran</a>

                    <div class="footer-social">
                        <a href=""><i class="fa-brands fa-facebook"></i></a>
                        <a href=""><i class="fa-brands fa-twitter"></i></a>
                        <a href=""><i class="fa-brands fa-google"></i></a>
                        <a href=""><i class="fa-brands fa-instagram"></i></a>

                    </div>
                </div>

                <!-- link -->
                <div class="footer-links">
                    <strong>Sản phẩm</strong>
                    <ul>
                        <li><a href="">Sản phẩm các loại</a></li>
                        <li><a href="">Gói ưu đãi</a></li>
                        <li><a href="">Phổ biến</a></li>
                        <li><a href="">Mới</a></li>
                    </ul>
                </div>

                <div class="footer-links">
                    <strong>Loại sản phẩm</strong>
                    <ul>
                        <li><a href="">Thịt và cá</a></li>
                        <li><a href="">Hạt giống</a></li>
                        <li><a href="">Sữa</a></li>
                        <li><a href="">Nấu ăn</a></li>
                    </ul>
                </div>

                <div class="footer-links">
                    <strong>Thông tin</strong>
                    <ul>
                        <li><a href="">Phone: 19001508</a></li>
                        <li><a href="">Email: MinhTran@gmail.com</a></li>
                    </ul>
                </div>
            </div>
        </footer>
        <section id="chat-box">
            <div class="chat">
                <i class="fa-solid fa-message"></i>
                <p></p>
            </div>
            <div class="chat-window hidden">
                <div class="chat-header">
                    <h4>Hỗ trợ trực tuyến</h4>
                    <span class="close-chat">X</span>
                </div>
                <div class="chat-body" id="customerChatBody">
                    <p>Bạn cần hỗ trợ gì không?</p>
                </div>
                <div class="chat-footer">
                    <input type="text" id="customerMessageInput" placeholder="Nhập tin nhắn...">
                    <button onclick="sendMessageToAdmin()">Gửi</button>
                </div>
            </div>
        </section>
        

    <script src="~/js/tt_product.js"></script>
    <script src="~/js/theme.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.3/signalr.min.js"></script>
    <script>
        function showContent(id) {
            var contents = document.querySelectorAll('.content > div');
            contents.forEach(function (content) {
                content.classList.add('hidden');
            });
            document.getElementById(id).classList.remove('hidden');
        }
    </script>
    <script>
        // Hàm cập nhật số lượng giỏ hàng qua AJAX
        function updateCartQuantity() {
            $.ajax({
                url: '@Url.Action("BagCart", "Function")',
                type: 'GET',
                success: function (result) {
                    $('#cartQuantity').text(result.quantity);  // Thay đổi số lượng giỏ hàng
                },
                error: function () {
                    console.log("Lỗi khi tải số lượng giỏ hàng");
                }
            });
        }

        // Gọi updateCartQuantity khi trang tải
        $(document).ready(function () {
            updateCartQuantity();
        });

        // Gọi updateCartQuantity khi sản phẩm được thêm vào giỏ hàng
        $('body').on('click', '.add-to-cart-button', function () {
            updateCartQuantity();
        });

        //AJAX chat
        document.querySelector('.chat').addEventListener('click', function () {
            const chatWindow = document.querySelector('.chat-window');
            if (chatWindow.style.display === 'none' || chatWindow.classList.contains('hidden')) {
                chatWindow.style.display = 'block';
                chatWindow.classList.remove('hidden');
            } else {
                chatWindow.style.display = 'none';
                chatWindow.classList.add('hidden');
            }
        });

        document.querySelector('.close-chat').addEventListener('click', function () {
            const chatWindow = document.querySelector('.chat-window');
            chatWindow.style.display = 'none';
            chatWindow.classList.add('hidden');
        });


        //JS chat client từ khách hàng.
        // Khởi tạo kết nối SignalR
        const connection = new signalR.HubConnectionBuilder().withUrl("/chathub").build();

        connection.start().then(() => {
            // Lấy userId từ claim của khách hàng khi đăng nhập
            const userId = "@User.FindFirst("UserId")?.Value"; // Cách lấy userId từ claim
            connection.invoke("JoinCustomerGroup", userId).catch(err => console.error(err.toString())); // Gọi JoinCustomerGroup
        }).catch(err => console.error(err.toString()));



        // Hàm để hiển thị tin nhắn của khách hàng lên giao diện
        function sendMessageToAdmin() {
            const message = document.getElementById("customerMessageInput").value;
            const userId = '@User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value';
            if (message.trim() === "") return; // Kiểm tra nếu tin nhắn rỗng

            // Hiển thị tin nhắn của khách hàng trên giao diện
            const messageElement = document.createElement("p");
            messageElement.classList.add("sent");
            messageElement.innerText = message;
            document.getElementById("customerChatBody").appendChild(messageElement);

            // Gửi tin nhắn đến admin
            connection.invoke("SendMessage", userId, message).catch(err => console.error(err.toString()));

            // Xóa nội dung input sau khi gửi
            document.getElementById("customerMessageInput").value = "";
        }

        // Xử lý nhận tin nhắn từ admin và hiển thị trên giao diện khách hàng
        connection.on("ReceiveMessage", (userId, message) => {
            const messageElement = document.createElement("p");
            messageElement.classList.add("received");
            messageElement.innerText = message;
            document.getElementById("customerChatBody").appendChild(messageElement);
        });
    </script>
</body>
</html>